# Generated by Django 5.1.5 on 2025-02-17 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('MobileNumber', models.CharField(max_length=255, unique=True)),
                ('HomeNumber', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('DeveloperID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('MobileNumber', models.CharField(max_length=255, unique=True)),
                ('HomeNumber', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('TimeframeID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('DevelopmentStart', models.DateField(max_length=255)),
                ('DevelopmentEstimatedEnd', models.DateField(max_length=255)),
                ('-', models.DateField(auto_now=True, verbose_name=models.DateField(max_length=255))),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('BillingID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('AmountOwed', models.DecimalField(decimal_places=2, max_digits=100)),
                ('PaymentStatus', models.CharField(max_length=255)),
                ('DatePaid', models.DateField(max_length=255, null=True)),
                ('PaymentMethod', models.CharField(max_length=255, null=True)),
                ('ClientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebDev.client')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('WebsiteID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('WebsiteName', models.CharField(max_length=255)),
                ('WebsiteType', models.CharField(max_length=255)),
                ('WebsiteStatus', models.CharField(max_length=255)),
                ('ClientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebDev.client')),
                ('DeveloperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebDev.developers')),
                ('TimeframeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebDev.timeframe')),
            ],
        ),
    ]
