# Generated by Django 5.1.7 on 2025-03-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0006_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='ClientID',
        ),
    ]
