# Generated by Django 5.1.7 on 2025-03-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0012_delete_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website_details',
            name='TimeframeID',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='PaymentMethod',
        ),
        migrations.AddField(
            model_name='website_details',
            name='DueDate',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Timeframe',
        ),
    ]
