# Generated by Django 5.1.5 on 2025-03-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0017_remove_billing_datepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='PaymentStatus',
            field=models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID')], max_length=255),
        ),
    ]
