# Generated by Django 5.1.5 on 2025-03-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0018_alter_billing_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='PaymentStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=255),
        ),
    ]
