# Generated by Django 5.1.7 on 2025-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='MobileNumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='developers',
            name='MobileNumber',
            field=models.CharField(max_length=255),
        ),
    ]
