# Generated by Django 5.1.7 on 2025-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0002_alter_client_mobilenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='developers',
            name='Email',
            field=models.CharField(max_length=255),
        ),
    ]
