# Generated by Django 5.1.7 on 2025-03-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0003_alter_client_email_alter_developers_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteInfo',
            new_name='Website_details',
        ),
    ]
