# Generated by Django 5.1.7 on 2025-03-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0008_rename_clientid_website_details_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
            ],
        ),
    ]
