# Generated by Django 5.1.7 on 2025-03-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0010_delete_client_delete_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_details',
            name='DeveloperID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebDev.developers'),
        ),
        migrations.AlterField(
            model_name='website_details',
            name='TimeframeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebDev.timeframe'),
        ),
    ]
