# Generated by Django 5.1.7 on 2025-03-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0011_alter_website_details_developerid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
