# Generated by Django 5.1.7 on 2025-03-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0014_alter_website_details_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='DatePaid',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
