# Generated by Django 5.1.7 on 2025-03-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebDev', '0016_alter_website_details_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='DatePaid',
        ),
    ]
